//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnveronementNaws.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int ID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string Contenu { get; set; }
        public string User_mail { get; set; }
        public string User_name { get; set; }
        public Nullable<System.DateTime> CommentaireDate { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
