//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnveronementNaws.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestionner
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Tele { get; set; }
        public string Email { get; set; }
        public string User_id { get; set; }
        public string Prenom { get; set; }
        public string Statu { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
